name: Auto Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign.yml
